USE QLNVIEN
--1. TÌM CÁC NỮ NHÂN VIÊN SỐNG Ở TẠI THÀNH PHỐ HCM
SELECT HONV, TENLOT, TENNV, DIACHI,PHAI
FROM NHANVIEN
WHERE DIACHI LIKE '%TpHCM' AND PHAI='NU'
--2. TÌM TẤT CẢ NHÂN VIÊN CÓ MỨC LƯƠNG LỚN HƠN HOẶC BẰNG 2TR HOẶC BÉ HƠN HOẶC BẰNG 3TR
SELECT MANV, HONV,TENLOT,TENNV,MUCLUONG ,MUCLUONG*0.1 THUẾ
FROM NHANVIEN
WHERE MUCLUONG>=2000000 AND MUCLUONG<=3000000 
ORDER BY THUẾ DESC
--3. TÌM CÁC NHÂN VIÊN VÀ TUỔI CỦA HỌ TUỔI LỚN HƠN = 40 BÉ HƠN HOẶC BẰNG 60, SẮP XẾP GIẢM DẦN
SELECT MANV, HONV,TENLOT,TENNV, YEAR(GETDATE())-YEAR(NGAYSINH) TUOI
FROM NHANVIEN
WHERE YEAR(GETDATE())-YEAR(NGAYSINH)>=40 AND YEAR(GETDATE())-YEAR(NGAYSINH)<=60
ORDER BY TUOI DESC
--PHÉP KẾT
--4. CHO TÌM NHÂN VIÊN CỦA PHÒNG NGHIÊN CỨU
SELECT *FROM PHONGBAN
SELECT MANV, HONV, TENLOT,TENNV, PHONG,TENPHONG
FROM NHANVIEN N,PHONGBAN P
WHERE N.PHONG=P.MAPHONG AND TENPHONG='NGHIEN CUU'
--5. TÌM TRƯỞNG PHÒNG CỦA PHÒNG NGHIÊN CỨU
SELECT MANV, HONV, TENLOT,TENNV, PHONG,TENPHONG,TRUONGPHONG
FROM NHANVIEN N,PHONGBAN P
WHERE N.PHONG=P.MAPHONG AND TENPHONG='NGHIEN CUU' AND TRUONGPHONG=MANV
--6. TÌM NHÂN VIÊN LÀM VIỆC PHÒNG BAN TẠI HANOI
SELECT * FROM DIADIEMPHONG
SELECT MANV, HONV, TENLOT,TENNV, PHONG, TENPHONG, D.DIADIEM
FROM NHANVIEN N, PHONGBAN P, DIADIEMPHONG D
WHERE N.PHONG=P.MAPHONG AND D.MAPHONG=P.MAPHONG AND D.DIADIEM='HANOI'
--7. CHO BIẾT NHÂN VIÊN VÀ HỌ TÊN VÀ NGƯỜI QUẢN LÍ TRỰC TIẾP CỦA HỌ 
SELECT * FROM NHANVIEN
SELECT NV1.MANV, NV1.HONV, NV1.TENLOT,NV1.TENNV, NV1.PHONG, NV2.MANQL, NV2.HONV, NV2.TENLOT, NV2.TENNV
FROM NHANVIEN NV1, NHANVIEN NV2
WHERE NV1.MANQL=NV2.MANV 
--8. TÌM TÊN NHÂN VIÊN, TÊN TRƯỞNG PHÒNG VÀ PHÒNG BAN NHÂN VIÊN ĐÓ LÀM VIỆC
--9. TÌM TẤT CẢ NHÂN VIÊN THAM GIA VÀO ĐỀ ÁN ĐÀO TẠO 1 HAOWJC ĐÀO TẠO2
SELECT * FROM DEAN
SELECT * FROM PHANCONG
SELECT HONV,TENLOT,TENNV, P.MADA, TENDA
FROM NHANVIEN N, DEAN D, PHANCONG P
WHERE N.MANV=P.MANV AND D.MADA=P.MADA AND (TENDA='DAOTAO1' OR TENDA='DAOTAO2')
--PHÉP TOÀN TẬP HỢP
SELECT HONV,TENLOT,TENNV, P.MADA, TENDA
FROM NHANVIEN N, DEAN D, PHANCONG P
WHERE N.MANV=P.MANV AND D.MADA=P.MADA AND (TENDA='DAOTAO1')
INTERSECT --GIAO NHAU
SELECT HONV,TENLOT,TENNV, P.MADA, TENDA
FROM NHANVIEN N, DEAN D, PHANCONG P
WHERE N.MANV=P.MANV AND D.MADA=P.MADA AND (TENDA='DAOTAO2')
--11. TÌM NV THAM GIA CẢ 2 ĐỀ ÁN DAOTAO1 VÀ DAOTAO2

--12. TÌM NV K THAM GIA VÀO ĐỀ ÁN DAOTAO 1

SELECT HONV,TENLOT,TENNV, P.MADA, TENDA
FROM NHANVIEN N, DEAN D, PHANCONG P
WHERE N.MANV=P.MANV AND D.MADA=P.MADA
EXCEPT
SELECT HONV,TENLOT,TENNV, P.MADA, TENDA
FROM NHANVIEN N, DEAN D, PHANCONG P
WHERE N.MANV=P.MANV AND D.MADA=P.MADA AND (TENDA='DAOTAO1')
--TRUY VẤN LỒNG
--13. TÌM NHÂN VIÊN KHÔNG TGIA VÀO ĐỀ ÁN ĐÀO TẠO1
SELECT * FROM PHANCONG
SELECT NV.MANV,TENNV
FROM NHANVIEN NV
WHERE NV.MANV NOT IN
	(SELECT NV.MANV
	FROM NHANVIEN NV, PHANCONG P, DEAN D
	WHERE NV.MANV=P.MANV AND P.MADA=D.MADA AND TENDA='DAOTAO1')
--14. TÌM NHÂN VIÊN CÓ MỨC LƯƠNG LỚN HƠN BẤT KÌ NHÂN VIÊN NÀO CỦA PHÒNG NGHIÊN CỨU
SELECT MANV, TENNV,MUCLUONG
FROM NHANVIEN
WHERE MUCLUONG>ANY 
	(SELECT MUCLUONG
	FROM NHANVIEN NV, PHONGBAN P
	WHERE NV.PHONG=P.MAPHONG AND TENPHONG='NGHIEN CUU' )
--15. TÌM NV CÓ MỨC LƯƠNG CAO NHẤT
SELECT MANV,TENNV,MUCLUONG
FROM NHANVIEN NV, PHONGBAN P
WHERE NV.PHONG=P.MAPHONG AND TENPHONG='NGHIEN CUU'
AND MUCLUONG>=ALL
	(SELECT MUCLUONG
	FROM NHANVIEN NV, PHONGBAN P
	WHERE NV.PHONG=P.MAPHONG AND TENPHONG='NGHIEN CUU' )
