USE QLSVIEN

--1.TÌM CÁC MÔN HỌC (MAMH,TENMH, TINCHI, MAKHOA, TENKHOA)
-- ĐƯỢC QUẢN LÝ BỞI KHOA THỐNG KÊ TIN HỌC
SELECT *FROM MONHOC
SELECT MAMH, TENMH,TINCHI, K.MAKHOA,K.TENKHOA
FROM MONHOC M, KHOA K
WHERE (K.MAKHOA='TKTH' AND (M.MAKHOA=K.MAKHOA))

--2. CHO BIẾT KHOA (MAKHOA,TENKHOA...) QUẢN LÝ HỌC PHẦN CSDL_2111
SELECT K.MAKHOA, TENKHOA, HP.MAMH, TENMH
FROM KHOA K, HOCPHAN HP, MONHOC MH
WHERE K.MAKHOA = MH.MAKHOA AND HP.MAMH = MH.MAMH AND MAHP=2111

/* SELECT K.MAKHOA, TENKHOA, HP.MAMH, TENMH
FROM (KHOA K JOIN MONHOC MH ON K.MAKHOA = MH.MAKHOA) JOIN HOCPHAN HP ON HP.MA
WHERE MAHP=2111 */ -- SAI

-- 3. TÌM NHỮNG SINH VIÊN ĐÃ HỌC MÔN CSDL
SELECT SV.MASV, TENSV, TENMH, DIEM
FROM SINHVIEN SV,KETQUA KQ, HOCPHAN HP, MONHOC MH
WHERE SV.MASV = KQ.MASV AND KQ.MAHP = HP.MAHP AND HP.MAMH = MH.MAMH AND 
TENMH=N'Cơ sở dữ liệu' AND (DIEM>=5 AND DIEM<=9)

SELECT *FROM SINHVIEN WHERE TENSV NOT LIKE  N'%Bình%'

-- ORDER BY TT <ASC/DESC>
SELECT *
FROM KHOA 
-- WHERE
ORDER BY NAMTHANHLAP DESC, TENKHOA DESC

--PHÉP TOÁN TẬP HỢP
/*
UNION [ALL]: HỢP
INTERSECT [ALL]: GIAO
EXCEPT [ALL]: TRỪ */
-- TRUY VÂN 1 <PHÉP TOÁN TẬP HỢP> TRUY VẤN 2.

-- CHO BIẾT SV CHƯA HỌC MÔN CSDL 
SELECT SV.MASV, TENSV, TENMH
FROM SINHVIEN SV, KETQUA K, HOCPHAN H, MONHOC M
WHERE SV.MASV=K.MASV AND K.MAHP=H.MAHP AND H.MAMH=M.MAMH
EXCEPT
SELECT SV.MASV, TENSV, TENMH
FROM SINHVIEN SV, KETQUA K, HOCPHAN H, MONHOC M
WHERE SV.MASV=K.MASV AND K.MAHP=H.MAHP AND H.MAMH=M.MAMH AND TENMH=N'Cơ sở dữ liệu'

-- LỒNG PHÂN CẤP 
SELECT SV.MASV, TENSV, TENMH
FROM SINHVIEN SV, KETQUA K, HOCPHAN H, MONHOC M
WHERE SV.MASV=K.MASV AND K.MAHP=H.MAHP AND H.MAMH=M.MAMH
AND SV.MASV NOT IN  
	(SELECT SV.MASV
	FROM SINHVIEN SV, KETQUA K, HOCPHAN H, MONHOC M
	WHERE SV.MASV=K.MASV AND K.MAHP=H.MAHP AND H.MAMH=M.MAMH AND TENMH=N'Cơ sở dữ liệu')

SELECT * FROM KETQUA

-- LỒNG TƯƠNG QUAN
SELECT SV.MASV, TENSV, TENMH
FROM SINHVIEN SV, KETQUA K, HOCPHAN H, MONHOC M
WHERE SV.MASV=K.MASV AND K.MAHP=H.MAHP AND H.MAMH=M.MAMH
AND NOT EXISTS
	(SELECT SV.MASV
	FROM SINHVIEN SV, KETQUA K, HOCPHAN H, MONHOC M
	WHERE SV.MASV=K.MASV AND K.MAHP=H.MAHP AND H.MAMH=M.MAMH AND TENMH=N'Cơ sở dữ liệu')